name: Staging deploy (multi-server)
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Version to deploy to staging"
        default: "staging"
        required: false
        type: string
  workflow_call:
    inputs:
      VERSION:
        description: "Version to deploy to staging"
        default: "staging"
        required: false
        type: string
jobs:
  deploy:
    name: superhero
    uses: ./.github/workflows/ssh_deploy.yaml
    with:
      VERSION: ${{ inputs.VERSION }}
      CONTAINER_NAME: "staging-superhero-api-mainnet"
    secrets:
      AE_NETWORK_ID: "ae_mainnet"
      API_HOST_PORT: "3023"
      DB_DATABASE: "api"
      DEPLOY_HOST: ${{ secrets.STAG_DEPLOY_HOST }}
      DEPLOY_KEY: ${{ secrets.STAG_DEPLOY_KEY }}
      DEPLOY_USERNAME: ${{ secrets.STAG_DEPLOY_USERNAME }}
      DB_USER: ${{ secrets.STAG_DB_USER }}
      DB_PASSWORD: ${{ secrets.STAG_DB_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
      TRENDING_TAGS_API_KEY: ${{ secrets.STAG_TRENDING_TAGS_API_KEY }}
      X_CLIENT_ID: ${{ secrets.STAG_X_CLIENT_ID }}
      X_CLIENT_SECRET: ${{ secrets.STAG_X_CLIENT_SECRET }}
      PROFILE_REGISTRY_CONTRACT_ADDRESS: ${{ secrets.STAG_PROFILE_REGISTRY_CONTRACT_ADDRESS }}
      PROFILE_ATTESTATION_SIGNER_ADDRESS: ${{ secrets.STAG_PROFILE_ATTESTATION_SIGNER_ADDRESS }}
      PROFILE_ATTESTATION_PRIVATE_KEY: ${{ secrets.STAG_PROFILE_ATTESTATION_PRIVATE_KEY }}
